/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebsiteRouteRouteImport } from './routes/_website/route'
import { Route as PanelRouteRouteImport } from './routes/panel/route'
import { Route as WebsiteIndexRouteImport } from './routes/_website/index'
import { Route as WebsiteLoginRouteImport } from './routes/_website/login'
import { Route as PanelIndexRouteImport } from './routes/panel/index'
import { Route as PanelBillingRouteImport } from './routes/panel/billing'
import { Route as PanelDeveloperApiRouteImport } from './routes/panel/developer-api'
import { Route as PanelFeedbackRouteImport } from './routes/panel/feedback'
import { Route as PanelFraudCheckerRouteImport } from './routes/panel/fraud-checker'
import { Route as PanelProfileRouteImport } from './routes/panel/profile'
import { Route as PanelSubscriptionPlansRouteImport } from './routes/panel/subscription-plans'

const WebsiteRouteRoute = WebsiteRouteRouteImport.update({
  id: '/_website',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRouteRoute = PanelRouteRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteIndexRoute = WebsiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WebsiteRouteRoute,
} as any)
const WebsiteLoginRoute = WebsiteLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => WebsiteRouteRoute,
} as any)
const PanelIndexRoute = PanelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PanelRouteRoute,
} as any)
const PanelBillingRoute = PanelBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => PanelRouteRoute,
} as any)
const PanelDeveloperApiRoute = PanelDeveloperApiRouteImport.update({
  id: '/developer-api',
  path: '/developer-api',
  getParentRoute: () => PanelRouteRoute,
} as any)
const PanelFeedbackRoute = PanelFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => PanelRouteRoute,
} as any)
const PanelFraudCheckerRoute = PanelFraudCheckerRouteImport.update({
  id: '/fraud-checker',
  path: '/fraud-checker',
  getParentRoute: () => PanelRouteRoute,
} as any)
const PanelProfileRoute = PanelProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PanelRouteRoute,
} as any)
const PanelSubscriptionPlansRoute = PanelSubscriptionPlansRouteImport.update({
  id: '/subscription-plans',
  path: '/subscription-plans',
  getParentRoute: () => PanelRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof WebsiteIndexRoute
  '/panel': typeof PanelRouteRouteWithChildren
  '/login': typeof WebsiteLoginRoute
  '/panel/billing': typeof PanelBillingRoute
  '/panel/developer-api': typeof PanelDeveloperApiRoute
  '/panel/feedback': typeof PanelFeedbackRoute
  '/panel/fraud-checker': typeof PanelFraudCheckerRoute
  '/panel/profile': typeof PanelProfileRoute
  '/panel/subscription-plans': typeof PanelSubscriptionPlansRoute
  '/panel/': typeof PanelIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof WebsiteLoginRoute
  '/panel/billing': typeof PanelBillingRoute
  '/panel/developer-api': typeof PanelDeveloperApiRoute
  '/panel/feedback': typeof PanelFeedbackRoute
  '/panel/fraud-checker': typeof PanelFraudCheckerRoute
  '/panel/profile': typeof PanelProfileRoute
  '/panel/subscription-plans': typeof PanelSubscriptionPlansRoute
  '/': typeof WebsiteIndexRoute
  '/panel': typeof PanelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_website': typeof WebsiteRouteRouteWithChildren
  '/panel': typeof PanelRouteRouteWithChildren
  '/_website/login': typeof WebsiteLoginRoute
  '/panel/billing': typeof PanelBillingRoute
  '/panel/developer-api': typeof PanelDeveloperApiRoute
  '/panel/feedback': typeof PanelFeedbackRoute
  '/panel/fraud-checker': typeof PanelFraudCheckerRoute
  '/panel/profile': typeof PanelProfileRoute
  '/panel/subscription-plans': typeof PanelSubscriptionPlansRoute
  '/_website/': typeof WebsiteIndexRoute
  '/panel/': typeof PanelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/panel'
    | '/login'
    | '/panel/billing'
    | '/panel/developer-api'
    | '/panel/feedback'
    | '/panel/fraud-checker'
    | '/panel/profile'
    | '/panel/subscription-plans'
    | '/panel/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/panel/billing'
    | '/panel/developer-api'
    | '/panel/feedback'
    | '/panel/fraud-checker'
    | '/panel/profile'
    | '/panel/subscription-plans'
    | '/'
    | '/panel'
  id:
    | '__root__'
    | '/_website'
    | '/panel'
    | '/_website/login'
    | '/panel/billing'
    | '/panel/developer-api'
    | '/panel/feedback'
    | '/panel/fraud-checker'
    | '/panel/profile'
    | '/panel/subscription-plans'
    | '/_website/'
    | '/panel/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  WebsiteRouteRoute: typeof WebsiteRouteRouteWithChildren
  PanelRouteRoute: typeof PanelRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_website': {
      id: '/_website'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WebsiteRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_website/': {
      id: '/_website/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WebsiteIndexRouteImport
      parentRoute: typeof WebsiteRouteRoute
    }
    '/_website/login': {
      id: '/_website/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof WebsiteLoginRouteImport
      parentRoute: typeof WebsiteRouteRoute
    }
    '/panel/': {
      id: '/panel/'
      path: '/'
      fullPath: '/panel/'
      preLoaderRoute: typeof PanelIndexRouteImport
      parentRoute: typeof PanelRouteRoute
    }
    '/panel/billing': {
      id: '/panel/billing'
      path: '/billing'
      fullPath: '/panel/billing'
      preLoaderRoute: typeof PanelBillingRouteImport
      parentRoute: typeof PanelRouteRoute
    }
    '/panel/developer-api': {
      id: '/panel/developer-api'
      path: '/developer-api'
      fullPath: '/panel/developer-api'
      preLoaderRoute: typeof PanelDeveloperApiRouteImport
      parentRoute: typeof PanelRouteRoute
    }
    '/panel/feedback': {
      id: '/panel/feedback'
      path: '/feedback'
      fullPath: '/panel/feedback'
      preLoaderRoute: typeof PanelFeedbackRouteImport
      parentRoute: typeof PanelRouteRoute
    }
    '/panel/fraud-checker': {
      id: '/panel/fraud-checker'
      path: '/fraud-checker'
      fullPath: '/panel/fraud-checker'
      preLoaderRoute: typeof PanelFraudCheckerRouteImport
      parentRoute: typeof PanelRouteRoute
    }
    '/panel/profile': {
      id: '/panel/profile'
      path: '/profile'
      fullPath: '/panel/profile'
      preLoaderRoute: typeof PanelProfileRouteImport
      parentRoute: typeof PanelRouteRoute
    }
    '/panel/subscription-plans': {
      id: '/panel/subscription-plans'
      path: '/subscription-plans'
      fullPath: '/panel/subscription-plans'
      preLoaderRoute: typeof PanelSubscriptionPlansRouteImport
      parentRoute: typeof PanelRouteRoute
    }
  }
}

interface WebsiteRouteRouteChildren {
  WebsiteLoginRoute: typeof WebsiteLoginRoute
  WebsiteIndexRoute: typeof WebsiteIndexRoute
}

const WebsiteRouteRouteChildren: WebsiteRouteRouteChildren = {
  WebsiteLoginRoute: WebsiteLoginRoute,
  WebsiteIndexRoute: WebsiteIndexRoute,
}

const WebsiteRouteRouteWithChildren = WebsiteRouteRoute._addFileChildren(
  WebsiteRouteRouteChildren,
)

interface PanelRouteRouteChildren {
  PanelBillingRoute: typeof PanelBillingRoute
  PanelDeveloperApiRoute: typeof PanelDeveloperApiRoute
  PanelFeedbackRoute: typeof PanelFeedbackRoute
  PanelFraudCheckerRoute: typeof PanelFraudCheckerRoute
  PanelProfileRoute: typeof PanelProfileRoute
  PanelSubscriptionPlansRoute: typeof PanelSubscriptionPlansRoute
  PanelIndexRoute: typeof PanelIndexRoute
}

const PanelRouteRouteChildren: PanelRouteRouteChildren = {
  PanelBillingRoute: PanelBillingRoute,
  PanelDeveloperApiRoute: PanelDeveloperApiRoute,
  PanelFeedbackRoute: PanelFeedbackRoute,
  PanelFraudCheckerRoute: PanelFraudCheckerRoute,
  PanelProfileRoute: PanelProfileRoute,
  PanelSubscriptionPlansRoute: PanelSubscriptionPlansRoute,
  PanelIndexRoute: PanelIndexRoute,
}

const PanelRouteRouteWithChildren = PanelRouteRoute._addFileChildren(
  PanelRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  WebsiteRouteRoute: WebsiteRouteRouteWithChildren,
  PanelRouteRoute: PanelRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
